name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2-texlive2022
        with:
          working_directory: cheatsheet
          root_file: main.tex
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cheatsheet/main.pdf
      
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.event.repository.name }} - Release ${{ github.run_number }}
          tag_name: ${{ github.run_number }}
          body: ${{ github.event.head_commit.message }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cheatsheet/main.pdf
          asset_name: ${{ github.event.repository.name }}.pdf
          asset_content_type: application/zip
      
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gha-build # The branch name where you want to push the assets
          FOLDER: cheatsheet # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
