name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: version
        run: echo "${{github.ref_name}}"
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.version }}
        
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2-texlive2022
        with:
          working_directory: cheatsheet
          root_file: main.tex
      
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: PDF
          path: cheatsheet/main.pdf
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body: CHANGES!
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: cheatsheet/main.pdf
          asset_name: cheatsheet.pdf
          asset_content_type: application/zip
